
export default {
    SET_LIBRARY: 'SET_LIBRARY',
    SET_NOW_PLAYING: 'SET_NOW_PLAYING',
    SET_CURRENT_VIEW: 'SET_CURRENT_VIEW',
    SET_FOLDERS: 'SET_FOLDERS',
    SET_PLAYLISTS: 'SET_PLAYLISTS',
    SET_LAST_LOOKED_AT: 'SET_LAST_LOOKED_AT',
    SET_RECENTLY_VIEWED_PLAYLIST: 'SET_RECENTLY_VIEWED_PLAYLIST',
    SET_RECENTLY_VIEWED_FOLDER: 'SET_RECENTLY_VIEWED_FOLDER',
    SET_QUEUE: 'SET_QUEUE',
    SET_HISTORY: 'SET_HISTORY',
    SET_DRAGGED_FILE: 'SET_DRAGGED_FILE',
    SET_VOLUME: 'SET_VOLUME',
    TOGGLE_MUTE: 'TOGGLE_MUTE',
    TOGGLE_REPEAT: 'TOGGLE_REPEAT',
    TOGGLE_SHUFFLE: 'TOGGLE_SHUFFLE',
    SET_PLAYBACK_SPEED: 'SET_PLAYBACK_SPEED',
    SET_SEARCH_STRING: 'SET_SEARCH_STRING'
}