
export default {
    SET_LIBRARY: 'SET_LIBRARY',
    SET_NOW_PLAYING: 'SET_NOW_PLAYING',
    SET_CURRENT_VIEW: 'SET_CURRENT_VIEW',
    SET_FOLDERS: 'SET_FOLDERS',
    SET_PLAYLISTS: 'SET_PLAYLISTS',
    SET_LAST_LOOKED_AT: 'SET_LAST_LOOKED_AT',
    SET_RECENTLY_VIEWED_PLAYLIST: 'SET_RECENTLY_VIEWED_PLAYLIST',
    SET_RECENTLY_VIEWED_FOLDER: 'SET_RECENTLY_VIEWED_FOLDER'
}